apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef: 
    name: "*"
  privileges: 
    - "ALL"
  database: "*"
  table: "*"
  username: celes
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
