apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: MARIA_ROOT_PASSWORD
    generate: true

  username: celes 
  passwordSecretKeyRef:
    name: mariadb-secret
    key: MARIA_USER_PASSWORD
    generate: true
  database: mariadb

  image: mariadb:latest
  imagePullPolicy: IfNotPresent

  port: 3306

  storage:
    size: 10Gi

  service:
    type: LoadBalancer
    metadata:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  metrics:
    enabled: true
