apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress-dev
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb 
  passwordSecretKeyRef:
    name: mariadb-secret
    key: MARIA_USER_PASSWORD
  # This field is immutable and defaults to 10
  maxUserConnections: 20
  host: "%"
  retryInterval: 5s
